/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

      bookQuotes test=new bookQuotes("null", "Carl Sagan");
    @Test
    public void jsonFileReadTest(){
        String output=test.toString();
        String expected="bookQuotes{quotes='null', author='Carl Sagan'}";
        assertEquals(output,expected);
    }
}
