/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.util.concurrent.ThreadLocalRandom;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {


        //access json file
        Reader fileReader = new FileReader(new File("D:\\401\\quotes\\app\\src\\main\\resources\\ recentquotes.json"));
        Gson gson = new Gson();
        // make a quote array filled with quotes from the json file.
        bookQuotes[] quotesArr = gson.fromJson(fileReader, bookQuotes[].class);
       int indexOfQuotes= ThreadLocalRandom.current().nextInt(quotesArr.length);
        System.out.println(quotesArr[indexOfQuotes]);



    }
}
